<?php
/**
 * WLC Member Privileges Controller
 *
 * Provides partner-specific privileges and promotional offers via REST API.
 * Ensures partner-specific filtering so each partner page receives ONLY its own offers.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

class WLC_Core_Privileges_Controller {

    /**
     * Get all partners or single partner if 'partner' query parameter or URL param is present
     */
    public function get_privileges( $request ) {
        $partner_slug = $request->get_param( 'partner' );
        if ( empty( $partner_slug ) ) {
            $partner_slug = $request->get_param( 'slug' );
        }

        $all_partners = self::get_all_partner_records();

        // If specific partner requested, return ONLY that partner's data & offers
        if ( ! empty( $partner_slug ) ) {
            $slug_clean = sanitize_title( $partner_slug );
            foreach ( $all_partners as $p ) {
                if ( $p['slug'] === $slug_clean || strval( $p['id'] ) === strval( $partner_slug ) ) {
                    return Wellness_API_Response::success( array(
                        'success' => true,
                        'partner' => $p,
                        'offers'  => $p['offers'],
                    ) );
                }
            }

            return new WP_Error(
                'partner_not_found',
                'Partner with the specified slug or ID was not found.',
                array( 'status' => 404 )
            );
        }

        // Return full list of partners
        return Wellness_API_Response::success( array(
            'success'  => true,
            'count'    => count( $all_partners ),
            'partners' => $all_partners,
        ) );
    }

    /**
     * Get static / database dataset of all partners and their specific offers
     */
    public static function get_all_partner_records() {
        return array(
            array(
                'id'            => 1,
                'slug'          => 'niraamaya-retreats-surya-samudra',
                'name'          => 'Niraamaya Retreats Surya Samudra',
                'location'      => 'Kovalam, Trivandrum, Kerala',
                'region'        => 'SOUTH INDIA',
                'shortDesc'     => 'A cliffside luxury heritage sanctuary overlooking the Arabian Sea, renowned for authentic Ayurvedic healing, lush cliff-edge cottages, and pristine coastal wellness.',
                'category'      => 'Ayurvedic Sanctuary & Coastal Resort',
                'image'         => '/images/niraamaya-retreat-real.webp',
                'flag'          => '🇮🇳',
                'website'       => 'https://www.niraamaya.com/surya-samudra-kovalam-retreat/',
                'bookingPeriod' => 'Valid for Booking and Travel upto 31st March 2027',
                'offers'        => array(
                    array(
                        'id'          => 'nss-1',
                        'title'       => 'Exclusive 20% Savings on Ayurveda Wellness Packages',
                        'discount'    => '20% SAVINGS',
                        'badge'       => 'Ayurveda Wellness',
                        'duration'    => '5, 7, 14, or 21 Nights',
                        'description' => 'Enjoy 20% savings on thoughtfully curated Full Board Ayurveda programs offering a holistic and immersive wellness journey.',
                        'inclusions'  => array(
                            'Accommodation in a well-appointed luxury room/cottage',
                            'Daily 90-minute Ayurvedic therapy, administered by a trained therapist',
                            'Daily 60-minute guided yoga session',
                            'Personalized consultation with an experienced Ayurveda physician',
                            'Prescribed internal herbal medications during the course of the program',
                            'Wholesome meals (breakfast, lunch, and dinner) based on a customized Ayurvedic diet plan',
                            'Round-trip transfers from the nearest airport or railway station',
                            'One Ayurvedic cooking session during the stay',
                            'One Yoga Nidra session during the stay',
                            'Complimentary high-speed Wi-Fi access',
                            '50% savings on laundry services',
                        ),
                        'terms'       => 'Applicable on 5, 7, 14, or 21-night packages. Booking and travel valid upto 31st March 2027.',
                    ),
                ),
            ),
            array(
                'id'            => 2,
                'slug'          => 'niraamaya-retreats-backwaters-beyond',
                'name'          => 'Niraamaya Retreats Backwaters & Beyond',
                'location'      => 'Kumarakom, Kerala',
                'region'        => 'SOUTH INDIA',
                'shortDesc'     => 'Nestled along the tranquil banks of Lake Vembanad, offering nature-immersed luxury villas, authentic Ayurvedic therapies, and serene backwater healing.',
                'category'      => 'Backwater Resort & Spa',
                'image'         => '/images/niraamaya-backwaters-spa.webp',
                'flag'          => '🇮🇳',
                'website'       => 'https://www.niraamaya.com/backwaters-and-beyond-kumarakom-resort/',
                'bookingPeriod' => 'Valid for Booking and Travel upto 31st March 2027',
                'offers'        => array(
                    array(
                        'id'          => 'nbb-1',
                        'title'       => 'Exclusive 20% Savings on Ayurveda Wellness Packages',
                        'discount'    => '20% SAVINGS',
                        'badge'       => 'Ayurveda Wellness',
                        'duration'    => '5, 7, 14, or 21 Nights',
                        'description' => 'Enjoy 20% savings on thoughtfully curated Full Board Ayurveda programs overlooking the Vembanad Lake.',
                        'inclusions'  => array(
                            'Accommodation in a well-appointed luxury room/villa',
                            'Daily 90-minute Ayurvedic therapy, administered by a trained therapist',
                            'Daily 60-minute guided yoga session',
                            'Personalized consultation with an Ayurveda physician',
                            'Prescribed internal herbal medications during the course of the program',
                            'Wholesome meals (breakfast, lunch, and dinner) based on a customized Ayurvedic diet plan',
                            'Round-trip transfers from the nearest airport or railway station',
                            'One Ayurvedic cooking session during the stay',
                            'One Yoga Nidra session during the stay',
                            'Complimentary high-speed Wi-Fi access',
                            '50% savings on laundry services',
                        ),
                        'terms'       => 'Applicable on 5, 7, 14, or 21-night packages. Booking and travel valid upto 31st March 2027.',
                    ),
                ),
            ),
            array(
                'id'        => 3,
                'slug'      => 'swastik-luxury-wellbeing-sanctuary',
                'name'      => 'Swastik Luxury Wellbeing Sanctuary',
                'location'  => 'Pune, Maharashtra',
                'region'    => 'WEST INDIA',
                'shortDesc' => 'An exclusive holistic retreat nestled in pristine Sahyadri hills, integrating ancient Vedic traditions, sacred healing rituals, and bespoke luxury sanctuaries.',
                'category'  => 'Holistic Sanctuary & Wellbeing',
                'image'     => '/images/swastik-sanctuary-real.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://swastiksanctuary.com',
                'offers'    => array(
                    array(
                        'id'          => 'sws-1',
                        'title'       => '20% Discount on Wellness Programs (3+ Nights)',
                        'discount'    => 'FLAT 20% OFF',
                        'badge'       => 'Published Rates',
                        'description' => 'Flat 20% discount on published rates for all immersive wellness and healing programs of 3 nights and above.',
                        'terms'       => 'Valid on 3-night, 5-night, 7-night, and 14-night holistic residential programs.',
                    ),
                    array(
                        'id'          => 'sws-2',
                        'title'       => 'Complimentary Guha Upgrade (5+ Nights)',
                        'discount'    => 'FREE UPGRADE',
                        'badge'       => 'Room Privilege',
                        'description' => 'Complimentary upgrade to the next Guha sanctuary category for stays of 5 nights and above.',
                        'terms'       => 'Subject to category availability at time of confirmed reservation.',
                    ),
                    array(
                        'id'          => 'sws-3',
                        'title'       => 'Complimentary Signature Experiences',
                        'discount'    => 'INCLUDED COMPLIMENTARY',
                        'badge'       => 'Sacred Rituals',
                        'description' => 'Additional complimentary signature experiences including Swastik Swagat, Swastik Shuddhi, and Swastik Agnihotra.',
                        'terms'       => 'Included automatically for all WLC verified members during their stay.',
                    ),
                ),
            ),
            array(
                'id'        => 4,
                'slug'      => 'viveda-wellness-resort',
                'name'      => 'Viveda Wellness Resort',
                'location'  => 'Nashik, Maharashtra',
                'region'    => 'WEST INDIA',
                'shortDesc' => 'An integrated wellness village surrounded by the Sahyadri mountains, specializing in Naturopathy, Ayurveda, Yoga, and personalized restorative living.',
                'category'  => 'Integrated Naturopathy & Wellness',
                'image'     => '/images/viveda-resort-real.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://vivedawellness.com',
                'offers'    => array(
                    array(
                        'id'          => 'viv-1',
                        'title'       => 'Viveda Destress & Unwind Program',
                        'discount'    => '20% SAVINGS',
                        'badge'       => '3-Night Retreat',
                        'description' => '20% savings on the comprehensive 3-night Viveda Destress & Unwind wellness retreat program.',
                        'terms'       => 'Includes doctor consultations, prescribed therapies, satvik dining, and villa stay.',
                    ),
                    array(
                        'id'          => 'viv-2',
                        'title'       => 'Viveda Pamper Yourself Package',
                        'discount'    => '15% SAVINGS',
                        'badge'       => 'Pampering Package',
                        'description' => '15% savings on the signature Viveda Pamper Yourself Package featuring organic skin rituals, aromatic massages, and herbal baths.',
                        'terms'       => 'Advance booking required. Valid for direct WLC member reservations.',
                    ),
                    array(
                        'id'          => 'viv-3',
                        'title'       => 'Welcome Inclusions & Yoga',
                        'discount'    => 'COMPLIMENTARY',
                        'badge'       => 'Arrival Privilege',
                        'description' => 'Welcome gift on arrival and one 30-minute personalised yoga session with resident yogic masters.',
                        'terms'       => 'Included with all member stays.',
                    ),
                ),
            ),
            array(
                'id'        => 5,
                'slug'      => 'the-wellness-co-karma-lakelands',
                'name'      => 'The Wellness Co. — Karma Lakelands',
                'location'  => 'Karma Lakelands, Gurgaon',
                'region'    => 'NORTH INDIA',
                'shortDesc' => 'A premier integrated longevity and medical wellness sanctuary combining cutting-edge biohacking, cryotherapy, and natural tranquility.',
                'category'  => 'Longevity & Integrated Wellness',
                'image'     => '/images/wellness-co-real.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://thewellnessco.in',
                'offers'    => array(
                    array(
                        'id'          => 'twc-kl-1',
                        'title'       => 'Signature Retreat Programs',
                        'discount'    => '40% SAVINGS',
                        'badge'       => 'Retreat Programs',
                        'description' => '40% savings on all 2-Day, 3-Day, 5-Day, and 7-Day Signature Wellness Retreat Programs.',
                        'terms'       => 'Valid on all 2D, 3D, 5D, and 7D residential retreat programs at Karma Lakelands.',
                    ),
                    array(
                        'id'          => 'twc-kl-2',
                        'title'       => 'Individual Wellness Therapies & Services',
                        'discount'    => '50% SAVINGS',
                        'badge'       => 'Individual Therapies',
                        'description' => '50% savings on all individual wellness therapies, recovery treatments, IV drips, and functional wellness services.',
                        'terms'       => 'Applicable on à la carte services at the Karma Lakelands centre.',
                    ),
                ),
            ),
            array(
                'id'        => 6,
                'slug'      => 'the-wellness-co-pan-india',
                'name'      => 'The Wellness Co. — PAN India',
                'location'  => 'PAN India (Centres Nationwide)',
                'region'    => 'NORTH INDIA',
                'shortDesc' => 'India\'s foremost network of advanced longevity clinics providing non-invasive recovery, cryo-wellness, and molecular rejuvenation.',
                'category'  => 'Longevity & Cryo Clinics',
                'image'     => '/images/wellness-co-spa.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://thewellnessco.in',
                'offers'    => array(
                    array(
                        'id'            => 'twc-pan-1',
                        'title'         => '5 General Wellness Therapies + 1 CRYO Facial',
                        'discount'      => '58% SAVINGS',
                        'badge'         => 'Special Package',
                        'originalPrice' => '₹34,125',
                        'memberPrice'   => '₹14,500',
                        'priceNote'     => 'All Inclusive',
                        'description'   => 'Comprehensive recovery package including 5 General Wellness Therapies (Infrared Sauna / Pressotherapy / Red Light) plus 1 Cryo Facial.',
                        'terms'         => 'Redeemable across all active The Wellness Co. clinics nationwide in India.',
                    ),
                ),
            ),
            array(
                'id'        => 7,
                'slug'      => 'silhouette-salon',
                'name'      => 'Silhouette Salon',
                'location'  => 'Gurgaon & Parfaire Tivoli, Delhi NCR',
                'region'    => 'NORTH INDIA',
                'shortDesc' => 'High-end bespoke hair styling, luxury salon aesthetics, and indulgent personal care rituals in premium Gurgaon and Tivoli spaces.',
                'category'  => 'Luxury Hair & Beauty Salon',
                'image'     => '/images/silhouette-salon-spa.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://silhouettesalon.in',
                'offers'    => array(
                    array(
                        'id'          => 'sil-1',
                        'title'       => 'Gurgaon Salon Services',
                        'discount'    => '20% DISCOUNT',
                        'badge'       => 'Gurgaon Centre',
                        'description' => '20% discount on all premium salon styling, treatments, manicures, pedicures, and grooming services in Gurgaon.',
                        'terms'       => 'Valid on all standard salon services upon displaying digital WLC membership.',
                    ),
                    array(
                        'id'          => 'sil-2',
                        'title'       => 'Parfaire Tivoli Privileges',
                        'discount'    => '25% DISCOUNT',
                        'badge'       => 'Parfaire Tivoli',
                        'description' => '25% discount on Parfaire Tivoli premium salon and spa treatments.',
                        'terms'       => 'Prior appointment recommended.',
                    ),
                ),
            ),
            array(
                'id'        => 8,
                'slug'      => 'viva-mayr',
                'name'      => 'Viva Mayr',
                'location'  => 'Maria Wörth / Altaussee, Austria',
                'region'    => 'INTERNATIONAL',
                'shortDesc' => 'World-renowned Austrian medical health institute on the pristine shores of Lake Wörthersee, pioneering Modern Mayr Medicine and longevity diagnostics.',
                'category'  => 'Medical Health & Longevity Institute',
                'image'     => '/images/vivamayr-austria-real.webp',
                'flag'      => '🇦🇹',
                'website'   => 'https://www.vivamayr.com',
                'offers'    => array(
                    array(
                        'id'          => 'vm-1',
                        'title'       => 'Stay 7 Nights + 2 Nights Free (Accommodation)',
                        'discount'    => '7 = 9 NIGHTS FREE',
                        'badge'       => 'Stay Extension',
                        'description' => 'Book a 7-night health residency at Viva Mayr and receive 2 additional nights complimentary on accommodation.',
                        'terms'       => 'Complimentary nights apply strictly to accommodation only.',
                    ),
                    array(
                        'id'          => 'vm-2',
                        'title'       => '€500 Package Discount',
                        'discount'    => '€500 SAVINGS',
                        'badge'       => 'Wellness Package',
                        'description' => 'A €500 discount on any 7-night wellness package.',
                        'terms'       => 'Valid on all 7-night comprehensive medical health packages.',
                    ),
                ),
            ),
            array(
                'id'        => 9,
                'slug'      => 'andaz-delhi-hyatt',
                'name'      => 'Andaz Delhi — Hyatt Hotel',
                'location'  => 'Hyatt Hotel, Vasant Vihar / Aerocity, Delhi',
                'region'    => 'NORTH INDIA',
                'shortDesc' => 'A luxury lifestyle Hyatt property blending contemporary Indian craftsmanship with urban wellness, heated pools, and artisanal spa sanctuaries.',
                'category'  => 'Urban Luxury Spa & Wellness',
                'image'     => '/images/andaz-hyatt-spa.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://www.hyatt.com/andaz/delaz-andaz-delhi',
                'offers'    => array(
                    array(
                        'id'          => 'and-1',
                        'title'       => '25% Off Regular Spa Treatments + 1 Hr Free Gym/Pool',
                        'discount'    => '25% OFF + 1 HR GYM/POOL',
                        'badge'       => 'Spa & Fitness',
                        'description' => '25% off on regular spa treatments (excluding packages) with one hour of complimentary Gym or pool access.',
                        'terms'       => 'Excluding packages. Valid on regular spa treatments with prior appointment.',
                    ),
                    array(
                        'id'          => 'and-2',
                        'title'       => 'Complimentary 30-Minute Add-On with 90-Minute Treatment',
                        'discount'    => 'FREE 30-MIN ADD-ON',
                        'badge'       => 'With 90-Min Treatment',
                        'description' => 'With any 90-minute treatment, add on 30 minutes of complimentary: head massage / face cleansing / foot massage or Chakra healing.',
                        'terms'       => 'Valid with any 90-minute treatment. Choose any one complimentary add-on.',
                    ),
                ),
            ),
            array(
                'id'        => 10,
                'slug'      => 'shangri-la-eros',
                'name'      => 'Shangri-La Eros',
                'location'  => 'Connaught Place, New Delhi',
                'region'    => 'NORTH INDIA',
                'shortDesc' => 'An iconic luxury five-star hotel in the diplomatic heart of Delhi, housing Chi The Spa and the state-of-the-art Wellness Club.',
                'category'  => '5-Star Luxury Hotel & Wellness Club',
                'image'     => '/images/shangri-la-stay.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://www.shangri-la.com/newdelhi/shangrila/',
                'offers'    => array(
                    array(
                        'id'          => 'sh-1',
                        'title'       => 'Exclusive Wellness Club Membership Offer (13 Months for Price of 12)',
                        'discount'    => '1 MONTH FREE (13 MONTHS TOTAL)',
                        'badge'       => 'Annual Membership',
                        'description' => 'Pay for 12 months and receive 1 additional month complimentary (total 13 months) on the rack rate of membership.',
                        'terms'       => 'Applicable on the rack rate of Wellness Club membership.',
                    ),
                    array(
                        'id'          => 'sh-2',
                        'title'       => 'Spa and Salon Privilege',
                        'discount'    => '20% DISCOUNT',
                        'badge'       => 'Chi The Spa & Salon',
                        'description' => 'Avail 20% discount on all spa treatments, massages, and salon rituals.',
                        'terms'       => 'Available on standard à la carte spa and salon menu.',
                    ),
                ),
            ),
            array(
                'id'        => 11,
                'slug'      => 'pema-wellness',
                'name'      => 'Pema Wellness',
                'location'  => 'Visakhapatnam, Andhra Pradesh, India',
                'region'    => 'EAST INDIA',
                'shortDesc' => 'A hilltop naturopathy and holistic healing resort overlooking the Bay of Bengal, offering evidence-based lifestyle medicine and bespoke longevity cures.',
                'category'  => 'Naturopathy & Holistic Healing Sanctuary',
                'image'     => '/images/pema-wellness-spa.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://pemawellness.co',
                'offers'    => array(
                    array(
                        'id'          => 'pem-1',
                        'title'       => '15% Discount on All Services & Retreats',
                        'discount'    => '15% DISCOUNT',
                        'badge'       => 'All Offerings',
                        'description' => '15% (Fifteen Percent) discount on wellness services, treatments, programs, retreats, and experiences offered by Pema Wellness.',
                        'terms'       => 'Applicable on residential retreat packages and outpatient wellness services.',
                    ),
                ),
            ),
            array(
                'id'        => 12,
                'slug'      => 'dhun-wellness-spa',
                'name'      => 'Dhun Wellness Spa',
                'location'  => 'Mumbai, Maharashtra, India',
                'region'    => 'WEST INDIA',
                'shortDesc' => 'An avant-garde urban sanctuary in Mumbai specializing in biohacking, thermal contrast recovery, infrared therapies, and cellular renewal.',
                'category'  => 'Biohacking & Thermal Recovery Sanctuary',
                'image'     => '/images/dhun-wellness-spa.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://dhunwellness.com',
                'offers'    => array(
                    array(
                        'id'          => 'dhun-1',
                        'title'       => 'Complimentary Recovery Session with 60-Min Service',
                        'discount'    => 'FREE RECOVERY SESSION',
                        'badge'       => 'Biohacking Privilege',
                        'description' => 'Book any 60-minute massage or any facial and receive one complimentary recovery treatment (infrared sauna, red light collagen bed or cryotherapy).',
                        'terms'       => 'One complimentary recovery treatment per 60-minute massage or facial booking.',
                    ),
                ),
            ),
            array(
                'id'        => 13,
                'slug'      => 'florian-hurel-hair-couture-spa',
                'name'      => 'Florian Hurel Hair Couture & Spa',
                'location'  => 'Mumbai, Ahmedabad, Hyderabad, Pune',
                'region'    => 'WEST INDIA',
                'shortDesc' => 'Celebrity hair stylist Florian Hurel\'s signature luxury salons, bringing international haute couture styling and bespoke spa rituals across India.',
                'category'  => 'Haute Coiffure & Luxury Spa',
                'image'     => '/images/community-experiences-lounge.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://florianhurelhaircouture.com',
                'offers'    => array(
                    array(
                        'id'          => 'fh-1',
                        'title'       => '20% Privilege Across All Salon & Spa Services',
                        'discount'    => '20% PRIVILEGE',
                        'badge'       => 'PAN India',
                        'description' => '20% privilege on all salon and spa services to all registered Wellness Lovers Club members.',
                        'terms'       => 'Applicable to all registered WLC members at Mumbai, Ahmedabad, Hyderabad, and Pune centres.',
                    ),
                ),
            ),
            array(
                'id'        => 14,
                'slug'      => 'tre-wellness',
                'name'      => 'Trē Wellness',
                'location'  => 'Hyderabad, Telangana, India',
                'region'    => 'SOUTH INDIA',
                'shortDesc' => 'An expansive holistic longevity and integrative wellness retreat nestled in tranquil nature outside Hyderabad, offering multi-day immersive programs.',
                'category'  => 'Integrative Longevity & Wellness Retreat',
                'image'     => '/images/wellness-retreat-cabin.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://trewellness.com',
                'offers'    => array(
                    array(
                        'id'          => 'tre-1',
                        'title'       => '3–6 Day & 6–9 Day Packages: 20% Off + Free Transfers',
                        'discount'    => '20% OFF + TRANSFERS',
                        'badge'       => '3-9 Day Packages',
                        'description' => '20% discount on published package rates + Complimentary round-trip transfers between Hyderabad Airport (or Hyderabad City) and Trē Wellness.',
                        'terms'       => 'Valid on all 3–6 Day and 6–9 Day published wellness packages.',
                    ),
                    array(
                        'id'          => 'tre-2',
                        'title'       => '10–14 Day, 15–21 Day & 28 Day Packages: 25% Off + Free Transfers',
                        'discount'    => '25% OFF + TRANSFERS',
                        'badge'       => '10-28 Day Packages',
                        'description' => '25% discount on published package rates + Complimentary round-trip transfers between Hyderabad Airport (or Hyderabad City) and Trē Wellness.',
                        'terms'       => 'Valid on long-stay intensive wellness and rejuvenation programs.',
                    ),
                    array(
                        'id'          => 'tre-3',
                        'title'       => 'Complimentary Stay Extension Days',
                        'discount'    => 'FREE EXTRA DAYS',
                        'badge'       => 'Stay Benefits',
                        'description' => '14-day package: Receive 1 complimentary additional day. 28-day package: Receive 2 complimentary additional days.',
                        'terms'       => 'Extension days include complimentary accommodation and standard retreat schedule.',
                    ),
                ),
            ),
            array(
                'id'        => 15,
                'slug'      => 'sawadhee-traditional-thai-spa',
                'name'      => 'Sawadhee Traditional Thai Spa',
                'location'  => 'Vasant Kunj, New Delhi, India',
                'region'    => 'NORTH INDIA',
                'shortDesc' => 'An authentic award-winning traditional Thai spa sanctuary providing deeply restorative royal Thai massages, herbal compresses, and body rituals.',
                'category'  => 'Authentic Thai Spa & Holistic Healing',
                'image'     => '/images/spa-healing-room.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://sawadhee.com',
                'offers'    => array(
                    array(
                        'id'          => 'saw-1',
                        'title'       => '20% Member Privilege on Spa Therapies',
                        'discount'    => '20% OFF',
                        'badge'       => 'Thai Healing',
                        'description' => '20% off on all authentic Thai spa treatments, signature body rituals, and holistic healing sessions.',
                        'terms'       => 'Valid on standard spa menu with advance appointment.',
                    ),
                ),
            ),
            array(
                'id'        => 16,
                'slug'      => 'iosis-spa-sorin',
                'name'      => 'IOSIS Spa & Sorin',
                'location'  => 'Mumbai, Guwahati, Raipur, etc. (PAN India)',
                'region'    => 'WEST INDIA',
                'shortDesc' => 'A premier chain of wellness spas and aesthetic wellness salons co-founded with wellness expertise, delivering head-to-toe rejuvenation across India.',
                'category'  => 'Wellness Spa & Aesthetic Care',
                'image'     => '/images/conscious-living.webp',
                'flag'      => '🇮🇳',
                'website'   => 'https://iosiswellness.com',
                'offers'    => array(
                    array(
                        'id'          => 'ios-1',
                        'title'       => '20% Off on All Services',
                        'discount'    => '20% OFF',
                        'badge'       => 'All Services',
                        'description' => '20% off on all services across IOSIS Spa & Sorin centres.',
                        'terms'       => 'Excluding retail products, memberships, packages, and existing promotional offers.',
                    ),
                    array(
                        'id'          => 'ios-2',
                        'title'       => 'Complimentary Face Sculpt & Foot Reflexology',
                        'discount'    => 'FREE 30-MIN TREATMENTS',
                        'badge'       => 'Per Eligible Visit',
                        'description' => 'A complimentary 15-minute Face Sculpt Massage and a 15-minute Foot Reflexology session with every eligible visit.',
                        'terms'       => 'Included complimentary with every eligible service visit for WLC members.',
                    ),
                ),
            ),
            array(
                'id'        => 17,
                'slug'      => 'hyatt-regency-hua-hin',
                'name'      => 'Hyatt Regency Hua Hin & THE BARAI Spa',
                'location'  => 'Prachuap Khiri Khan, Hua Hin, Thailand',
                'region'    => 'INTERNATIONAL',
                'shortDesc' => 'A breathtaking beachfront haven on the Gulf of Thailand, home to THE BARAI — an internationally acclaimed architectural and holistic wellness sanctuary.',
                'category'  => 'Luxury Coastal Wellness Sanctuary',
                'image'     => '/images/philosophy-resort.webp',
                'flag'      => '🇹🇭',
                'website'   => 'https://www.hyatt.com/hyatt-regency/en-US/huahi-hyatt-regency-hua-hin',
                'offers'    => array(
                    array(
                        'id'          => 'hrh-1',
                        'title'       => '20% Off Wellness Programs & Experiences',
                        'discount'    => '20% OFF',
                        'badge'       => 'THE BARAI Spa',
                        'description' => '20% off for any wellness program or experience at Hyatt Regency Hua Hin and THE BARAI.',
                        'terms'       => 'Applicable across wellness packages, mindful healing sessions, and spa journeys.',
                    ),
                ),
            ),
            array(
                'id'        => 18,
                'slug'      => 'losinj-hotels-villas-alhambra',
                'name'      => 'Lošinj Hotels & Villas (Boutique Hotel Alhambra)',
                'location'  => 'Alhambra, Čikat Bay, Lošinj Island, Croatia',
                'region'    => 'INTERNATIONAL',
                'shortDesc' => 'A member of the Small Luxury Hotels of the World, perched in fragrant Aleppo pine forests in Čikat Bay, celebrated for healing sea air, microclimate cures, and Cube Spa Alhambra.',
                'category'  => 'Ultra-Luxury Island Healing & Cube Spa',
                'image'     => '/images/luxury-stays-cabana.webp',
                'flag'      => '🇭🇷',
                'website'   => 'https://www.losinj-hotels.com/en/hotels-and-villas/boutique-hotel-alhambra/',
                'offers'    => array(
                    array(
                        'id'          => 'los-1',
                        'title'       => 'Complete Alhambra Wellness Experience Inclusions',
                        'discount'    => 'COMPREHENSIVE INCLUSIONS + 20% OFF FACIALS',
                        'badge'       => 'Island Sanctuary Inclusions',
                        'description' => 'An extraordinary island restorative experience encompassing forest therapy, herbal rituals, sea-salt hydrotherapy, and suite privileges.',
                        'inclusions'  => array(
                            'Herbs de Lošinj Tea Ceremony (15 minutes)',
                            'Aleppo Forest Bathing Therapy (60 minutes)',
                            'Kurhaus Inhalation Bar Ritual',
                            'Aleppo Pine Immunity Massage (60 minutes)',
                            '20% savings on facial treatments',
                            'Complimentary bicycle usage throughout stay',
                            'In-room artisanal bites inspired by local island flavours',
                            'Complimentary tickets to the Museum of Apoxyomenos',
                            'Full access to Cube Spa Alhambra: indoor seawater pool, sauna, Mediterranean bath, fitness and relaxation areas',
                            'Suite Privileges: Curated welcome gift, complimentary first minibar refill, Butler Service (selected suites, May–September), luxury transfers within Mali and Veli Lošinj (subject to availability)',
                        ),
                        'terms'       => 'All inclusions automatically provided for WLC member reservations. Transfers subject to availability.',
                    ),
                ),
            ),
            array(
                'id'        => 19,
                'slug'      => 'como-point-yamu',
                'name'      => 'COMO Point Yamu',
                'location'  => 'Phuket, Thailand',
                'region'    => 'INTERNATIONAL',
                'shortDesc' => 'Perched at the tip of Cape Yamu overlooking the sapphire waters of Phang Nga Bay, offering award-winning COMO Shambhala holistic wellness and Italian-Thai cuisine.',
                'category'  => 'COMO Shambhala Luxury Wellness Resort',
                'image'     => '/images/journey-wellness.webp',
                'flag'      => '🇹🇭',
                'website'   => 'https://www.comohotels.com/phuket/como-point-yamu',
                'offers'    => array(
                    array(
                        'id'          => 'cpy-1',
                        'title'       => 'Exclusive Member Inclusions & COMO Shambhala Wellness',
                        'discount'    => 'HALF-BOARD + COMPLIMENTARY SPA & EXPERIENCES',
                        'badge'       => 'COMO Shambhala Experience',
                        'description' => 'Experience serene luxury on Phang Nga Bay with comprehensive dining, daily wellness sessions, and signature massages included.',
                        'inclusions'  => array(
                            'Minimum three-night luxury stay at COMO Point Yamu',
                            'Half-board dining included (breakfast and dinner)',
                            'One complimentary 60-minute COMO Shambhala Massage per guest',
                            'One sunset cocktail experience during the stay',
                            'Daily access to COMO Shambhala wellness classes including yoga, movement, and guided activities',
                            'Full access to wellness centre facilities: 24-hour gym, steam room, hydrotherapy pool',
                            'In-room yoga and wellness sessions on demand',
                        ),
                        'terms'       => 'Minimum 3-night stay required. Inclusions apply per registered guest.',
                    ),
                ),
            ),
            array(
                'id'        => 20,
                'slug'      => 'como-uma-bhutan',
                'name'      => 'COMO Uma Paro & Punakha',
                'location'  => 'Paro & Punakha, Bhutan',
                'region'    => 'INTERNATIONAL',
                'shortDesc' => 'Two intimate luxury lodges in the mythical Kingdom of Bhutan, blending traditional Bhutanese craftsmanship with COMO Shambhala therapies and Himalayan tranquility.',
                'category'  => 'Himalayan Luxury Sanctuary & Cultural Wellness',
                'image'     => '/images/buddha-bg.webp',
                'flag'      => '🇧🇹',
                'website'   => 'https://www.comohotels.com/bhutan/como-uma-paro',
                'offers'    => array(
                    array(
                        'id'          => 'cub-1',
                        'title'       => 'Four-Course Private Dinner & Sacred Bhutanese Inclusions',
                        'discount'    => 'SACRED CEREMONY + DINNER & SPA UPGRADE',
                        'badge'       => 'Himalayan Experience',
                        'description' => 'Enjoy a four-course dinner complete with a bottle of house wine by firelight at COMO Uma Paro, or al fresco overlooking the river at COMO Uma Punakha.',
                        'inclusions'  => array(
                            'Blessing ceremony with 10 to 15 Buddhist monks',
                            'Traditional Bhutanese Gho and Kira clothing rental',
                            'Treatment upgrade to a 90-minute traditional hot stone bath and massage',
                            'Four-course private dinner including a complimentary bottle of house wine',
                        ),
                        'terms'       => 'Valid on stays at COMO Uma Paro or COMO Uma Punakha.',
                    ),
                ),
            ),
            array(
                'id'        => 21,
                'slug'      => 'ja-palm-tree-court',
                'name'      => 'JA Palm Tree Court & Calm Spa',
                'location'  => 'Jebel Ali Beach, Dubai, UAE',
                'region'    => 'INTERNATIONAL',
                'shortDesc' => 'An all-suite 5-star beachfront retreat surrounded by lush peacocks and palm gardens on the Arabian Gulf, housing the tranquil Calm Spa & Salon.',
                'category'  => 'Beachfront Resort & Calm Spa Sanctuary',
                'image'     => '/images/philosophy-pool.webp',
                'flag'      => '🇦🇪',
                'website'   => 'https://jaresortshotels.com/dubai/ja-the-resort/ja-palm-tree-court',
                'offers'    => array(
                    array(
                        'id'          => 'jpc-1',
                        'title'       => 'Unwind Longer at Calm Spa',
                        'discount'    => '60-MIN FREE EXTENSION',
                        'badge'       => 'Calm Spa Ritual',
                        'memberPrice' => 'AED 800',
                        'description' => '90-minute Deep Tissue Massage + Additional 60 minutes complimentary to extend your treatment or share with a guest.',
                        'terms'       => 'Priced at AED 800. Available Monday to Friday only.',
                    ),
                    array(
                        'id'          => 'jpc-2',
                        'title'       => 'Full Day Reset Package',
                        'discount'    => 'FULL DAY RETREAT + 20% OFF',
                        'badge'       => 'Day Retreat',
                        'memberPrice' => 'AED 650 (Mon–Fri) / AED 800 (Sat–Sun)',
                        'description' => 'Comprehensive day reset featuring 75-minute Stress Release Massage, gourmet three-course lunch on Signature Pool terrace, full thermal & beach access, and 20% savings on additional treatments and F&B.',
                        'inclusions'  => array(
                            '75-minute Stress Release Massage',
                            'Gourmet three-course set lunch on the Signature Pool terrace',
                            'Full access to jacuzzi, sauna, steam room and sensory shower experience',
                            'Access to serene pools and private resort beach',
                            '20% savings on additional spa treatments on the same day',
                            '20% savings on food and beverage at selected outlets on the same day',
                        ),
                        'terms'       => 'AED 650 per person Monday to Friday | AED 800 per person Saturday & Sunday.',
                    ),
                    array(
                        'id'          => 'jpc-3',
                        'title'       => 'Indulge without Limits at Calm Spa',
                        'discount'    => 'UNLIMITED MASSAGES + 30% OFF SALON',
                        'badge'       => 'Unlimited Wellness',
                        'memberPrice' => 'AED 800 (Mon–Fri) / AED 1,200 (Sat–Sun)',
                        'description' => 'Unlimited choice of 30, 60 and 90-minute massages with full wellness wet area access and beach privileges.',
                        'inclusions'  => array(
                            'Unlimited choice of 30, 60 and 90-minute massages during the day',
                            '30% savings on facials and salon treatments',
                            '15% savings on selected retail items',
                            '20% savings on food and beverage at selected outlets on the same day',
                            'Full access to jacuzzi, sauna, steam room, pools and private beach',
                        ),
                        'terms'       => 'AED 800 per person Monday to Friday | AED 1,200 per person Saturday & Sunday.',
                    ),
                ),
            ),
        );
    }
}
